import subprocess as sp

def gathering_info():
    arp_cmd = sp.run(["cmd","/c","arp","-a"], capture_output=True, text=True)
    print("==arp==")
    print(arp_cmd.stdout)
    hidden_file = sp.run(["cmd","/c", "dir", "/A:H"], capture_output=True, text=True)
    print("==hidden_file==")
    print(hidden_file.stdout)
    info = sp.run(["cmd","/c","systeminfo"], capture_output=True, text=True)
    print("==Info==")
    print(info.stdout)
    ipconfig = sp.run(["cmd","/c","ipconfig"],capture_output=True, text=True)
    print("==ipconfig==")
    print(ipconfig.stdout)
    hostname = sp.run(["cmd","/c","whoami"],capture_output=True, text=True)
    print("==hostname==")
    print(hostname.stdout)
    history = sp.run(["cmd","/c","doskey","/history"], capture_output=True, text=True)
    print("==history==")
    print(history.stdout)
    priv_info = sp.run(["cmd","/c","whoami","/priv"], capture_output=True, text=True)
    print("==priv_info==")
    print(priv_info.stdout)
    all_user = sp.run(["cmd","/c","net","user"],capture_output=True, text=True)
    print("==all_user==")
    print(all_user.stdout)
    all_group = sp.run(["cmd","/c","net", "localgroup"],capture_output=True, text=True)
    print("==all_group==")
    print(all_group.stdout)
    share_resource = sp.run(["cmd","/c","net", "share"], capture_output=True, text=True)
    print("==share_resource==")
    print(share_resource.stdout)
    display_env = sp.run(["cmd","/c","echo", "%PATH%"],capture_output=True, text=True)
    print("==display_env==")
    print(display_env.stdout)
    display_serv = sp.run(["cmd","/c","sc", "query"],capture_output=True, text=True)
    print("==display_serv==")
    print(display_serv.stdout)
    display_eventlog = sp.run(["cmd","/c","sc", "query", "eventlog"],capture_output=True, text=True)
    print("==event_log==")
    print(display_eventlog.stdout)
    display_windefend = sp.run(["cmd","/c","sc", "query", "windefend"], capture_output=True, text=True)
    print("==windefend==")
    print(display_windefend.stdout)
    view_task = sp.run(["cmd","/c","schtasks", "/Query"], capture_output=True, text=True)
    print("==view_task==")
    print(view_task.stdout)